apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.199.40
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/containerd/containerd.sock
  name: controller-0
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  KubeletExtraArgs:
    node-ip: 192.168.199.10
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "192.168.199.40:6443"
etcd:
    external:
        endpoints:
        - https://192.168.199.10:2379
        - https://192.168.199.11:2379
        - https://192.168.199.12:2379
        caFile: /etc/kubernetes/pki/etcd/ca.crt
        certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
        keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
networking:
  dnsDomain: cluster.local
  podSubnet: 10.32.0.0/16
  serviceSubnet: 10.96.0.0/12
dns:
  type: CoreDNS
